/**
 * data.ts — Server-side loaders for the committed JSON snapshots.
 *
 * Phase 1/2 source of truth is committed JSON, regenerated by GitHub Actions (tenders: daily,
 * awards: on-demand) and redeployed via Vercel's git integration. (Phase 3: heavier historical
 * contract-history data moves to Neon Postgres.)
 */
import "server-only";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Tender } from "./tenders";
import type { Award } from "./awards";

export interface TenderSnapshot {
  generatedAt: string;
  source: string;
  feedTotal: number;
  matched: number;
  tenders: Tender[];
}

export interface AwardSnapshot {
  generatedAt: string;
  source: string;
  feedTotal: number;
  matched: number;
  awards: Award[];
}

let tenderCache: TenderSnapshot | null = null;
let awardCache: AwardSnapshot | null = null;

export function getSnapshot(): TenderSnapshot {
  if (tenderCache) return tenderCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-tenders.json"), "utf-8");
    tenderCache = JSON.parse(raw) as TenderSnapshot;
  } catch {
    tenderCache = { generatedAt: "", source: "", feedTotal: 0, matched: 0, tenders: [] };
  }
  return tenderCache;
}

export function getTenders(): Tender[] {
  return getSnapshot().tenders;
}

export function getTenderByRef(ref: string): Tender | undefined {
  return getTenders().find((t) => t.ref === ref);
}

export function getAwardSnapshot(): AwardSnapshot {
  if (awardCache) return awardCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-awards.json"), "utf-8");
    awardCache = JSON.parse(raw) as AwardSnapshot;
  } catch {
    awardCache = { generatedAt: "", source: "", feedTotal: 0, matched: 0, awards: [] };
  }
  return awardCache;
}

export function getAwards(): Award[] {
  return getAwardSnapshot().awards;
}
