/**
 * data.ts - Server-side loaders for the committed JSON snapshots.
 *
 * Phase 1/2 source of truth is committed JSON, regenerated by GitHub Actions (tenders: daily,
 * awards: on-demand) and redeployed via Vercel's git integration. (Phase 3: heavier historical
 * contract-history data moves to Neon Postgres.)
 */
import "server-only";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Tender } from "./tenders";
import type { Award } from "./awards";
import type { StandingOffer } from "./standing-offers";
import type { BlueprintProject } from "./blueprint";
import type { ItbObligation } from "./itb";

export interface TenderSnapshot {
  generatedAt: string;
  source: string;
  feedTotal: number;
  matched: number;
  tenders: Tender[];
}

export interface AwardSnapshot {
  generatedAt: string;
  source: string;
  feedTotal: number;
  matched: number;
  awards: Award[];
}

export interface StandingOfferSnapshot {
  generatedAt: string;
  source: string;
  feedTotal: number;
  matched: number;
  offers: StandingOffer[];
}

export interface BlueprintSnapshot {
  generatedAt: string;
  source: string;
  total: number;
  projects: BlueprintProject[];
}

export interface ItbSnapshot {
  generatedAt: string;
  source: string;
  total: number;
  rows: ItbObligation[];
}

let tenderCache: TenderSnapshot | null = null;
let awardCache: AwardSnapshot | null = null;
let standingOfferCache: StandingOfferSnapshot | null = null;
let blueprintCache: BlueprintSnapshot | null = null;
let itbCache: ItbSnapshot | null = null;

export function getSnapshot(): TenderSnapshot {
  if (tenderCache) return tenderCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-tenders.json"), "utf-8");
    tenderCache = JSON.parse(raw) as TenderSnapshot;
  } catch {
    tenderCache = { generatedAt: "", source: "", feedTotal: 0, matched: 0, tenders: [] };
  }
  return tenderCache;
}

export function getTenders(): Tender[] {
  return getSnapshot().tenders;
}

export function getTenderByRef(ref: string): Tender | undefined {
  return getTenders().find((t) => t.ref === ref);
}

export function getAwardSnapshot(): AwardSnapshot {
  if (awardCache) return awardCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-awards.json"), "utf-8");
    awardCache = JSON.parse(raw) as AwardSnapshot;
  } catch {
    awardCache = { generatedAt: "", source: "", feedTotal: 0, matched: 0, awards: [] };
  }
  return awardCache;
}

export function getAwards(): Award[] {
  return getAwardSnapshot().awards;
}

export function getStandingOfferSnapshot(): StandingOfferSnapshot {
  if (standingOfferCache) return standingOfferCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-standing-offers.json"), "utf-8");
    standingOfferCache = JSON.parse(raw) as StandingOfferSnapshot;
  } catch {
    standingOfferCache = { generatedAt: "", source: "", feedTotal: 0, matched: 0, offers: [] };
  }
  return standingOfferCache;
}

export function getStandingOffers(): StandingOffer[] {
  return getStandingOfferSnapshot().offers;
}

export function getBlueprintSnapshot(): BlueprintSnapshot {
  if (blueprintCache) return blueprintCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-investment-plan.json"), "utf-8");
    blueprintCache = JSON.parse(raw) as BlueprintSnapshot;
  } catch {
    blueprintCache = { generatedAt: "", source: "", total: 0, projects: [] };
  }
  return blueprintCache;
}

export function getBlueprintProjects(): BlueprintProject[] {
  return getBlueprintSnapshot().projects;
}

export function getItbSnapshot(): ItbSnapshot {
  if (itbCache) return itbCache;
  try {
    const raw = readFileSync(join(process.cwd(), "data", "defence-itb-obligations.json"), "utf-8");
    itbCache = JSON.parse(raw) as ItbSnapshot;
  } catch {
    itbCache = { generatedAt: "", source: "", total: 0, rows: [] };
  }
  return itbCache;
}

export function getItbRows(): ItbObligation[] {
  return getItbSnapshot().rows;
}
